### PR TITLE
added five cards

### PR DESCRIPTION
**Pull request by bertintshisuaka2**

### CODE REVIEW

**Comment by bertintshisuaka2** [comment]
plz  review

**Comment by bertintshisuaka2** [comment]
created five cards , still working pn how to display map

**Comment by Git-Vdim-Hub** [comment]
Do not merge or it will break main/we will lose code.

**Review by Git-Vdim-Hub — CHANGES_REQUESTED** [review]
- weather does not work on your cards (need to call coordinates for weather and change weather ids for your cards
- maps does not work on your cards please talk to Junho for guidance on maps
- you removed the description styling from the last correct card
- partially duplicate card
- styling does not follow the other cards

**Review by gengamask — APPROVED** [review]

**Review by gengamask — APPROVED** [review]

**Review by Git-Vdim-Hub — APPROVED** [review]
reviewed code, approved.

**Pull request merged**
